# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
